apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: ninja
  name: devops-teste-ninja
spec:
  selector:
    matchLabels:
      component: ninja
  replicas: 2
  template:
    metadata:
      labels:
        component: ninja
    spec:
      containers:
      - name: lets-be-a-ninja
        image: __dockerimg__:latest

        resources:
          requests:
            cpu: "0.5"
            memory: 64Mi
          limits:
            cpu: "1"
            memory: 128Mi

        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          periodSeconds: 30
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 5

        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lb-ninja
spec:
  selector:
    component: ninja
  type: LoadBalancer
  ports:
  - name: goninja-lb
    port: 80
    protocol: TCP
    targetPort: 8000