apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: ninja
  name: devops-teste-ninja
spec:
  selector:
    matchLabels:
      component: ninja
  replicas: 2
  template:
    metadata:
      labels:
        component: ninja
    spec:
      containers:
      - name: lets-be-a-ninja
        image: PdockerimgP

        resources:
          requests:
            cpu: "0.5"
            memory: 64Mi
          limits:
            cpu: "1"
            memory: 128Mi

        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lb-ninja
spec:
  selector:
    component: ninja
  type: LoadBalancer
  ports:
  - name: goninja-lb
    port: 80
    protocol: TCP
    targetPort: 8000