variable "vpc_id" {}
variable "prefix" {}
variable "cluster_name" {}
variable retention_days {}
variable "subnet_ids" {}
variable "desired_size" {}
variable "desired_cluster" {}
variable "max_size" {}
variable "min_size" {}
variable "instance_types" {}