variable "prefix" {}
variable "vpc_cidr_block" {}
variable "cluster_name" {}
variable "retention_days" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_subnets" {}
variable "desired_cluster" {}
variable "instance_types" {}